# Generated by Django 3.2.5 on 2021-07-12 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=285)),
                ('discribe', models.CharField(max_length=285)),
                ('parent', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=285)),
                ('code', models.CharField(max_length=285)),
                ('amount', models.FloatField(max_length=285)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=285)),
                ('starting_cooking_time', models.TimeField()),
                ('stimated_cooking_time', models.TimeField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('deleted', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_items.categories')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_items.discount')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_items.price')),
            ],
        ),
    ]
