# Generated by Django 3.2.5 on 2021-07-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('total_discount', models.FloatField()),
                ('final_price', models.FloatField()),
                ('creat_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('deleted', models.BooleanField()),
            ],
        ),
    ]
